### PR TITLE
Add shell script best practices.

### PR DESCRIPTION
**Pull request by aude**
Used the shell script analysis tool "shellcheck" for improvement
suggestions.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2devbox-web?pullRequest=67) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/magento2devbox-web?pullRequest=67) before we can accept your contribution.<br/>

**Comment by o-iegorov** [comment]
@aude after applying your patch magento installation falls with

> [SUCCESS]: Magento installation complete.
> [SUCCESS]: Magento Admin URI: /admin
> Executing shell command:
> touch /home/magento2/configs/varnish/varnish_used
> touch: cannot touch '/home/magento2/configs/varnish/varnish_used': No such file or directory
> 
> 
>   [Exception]
>   Command failed to execute

Please update your patch

**Comment by aude** [comment]
The two files changed in my patch should not affect the `/home/magento2/configs/varnish/varnish_used` file. They do not even contain the words `varnish` or `configs`.

I tried to build the Docker image locally to reproduce your messages:

    $ docker build -t magento2devbox-web

I was not able to build it because of a segmentation fault in one of the C program compilations.

I am fairly sure the error you experienced is not a result of applying my patch.

**Comment by aude** [comment]
The reason the build process failed at my computer is that I am running a linux kernel hardened with [grsecurity](https://grsecurity.net/). So never mind the build failure from my part.

I am still fairly sure the error you experienced is not a result of applying my patch.

**Comment by alankent** [comment]
Thanks for the clean up! I noticed the lack of quotes around variables too - did not realize bash has [[ and ]] built in to avoid that problem. Nice!

**Pull request merged**
